export const PermissionActions = {
  XEM: 'XEM',
  SUA: 'SUA',
  XOA: 'XOA',
  THEM: 'THEM',
  XUATBAN: 'XUATBAN',
} as const;

export const permissionsList = {
  home: 'home',
  homeThongTinTaiKhoan: 'home_thong-tin-tai-khoan',
  homeDanhSachTaiKhoan: 'home_danh-sach-tai-khoan',
  homeThemTaiKhoan: 'home_them-moi-tai-khoan',
  homeChinhSuaTaiKhoan: 'home_chinh-sua-tai-khoan',
  thongKe: 'thong-ke',
  thongKeSoLieu: 'thong-ke_so-lieu',
  thongKeBieuDo: 'thong-ke_bieu-do',
  cauHinh: 'cau-hinh',
  cauHinhThongTin: 'cau-hinh_thong-tin',
  cauHinhPhanQuyen: 'cau-hinh_phan-quyen',
  khuPho: 'khu-pho',
  khuPhoToChucDanCu: 'khu-pho_to-chuc-dan-cu',
  khuPhoToChucDanCuBanDieuHanh: 'khu-pho_to-chuc-dan-cu_ban-dieu-hanh',
  khuPhoToChucDanCuDanCu: 'khu-pho_to-chuc-dan-cu_dan-cu',
  khuPhoTuyenTruyenPhanAnh: 'khu-pho_tuyen-truyen-phan-anh',
  khuPhoTuyenTruyenPhanAnhTinTucSuKien: 'khu-pho_tuyen-truyen-phan-anh_tin-tuc-su-kien',
  khuPhoTuyenTruyenPhanAnhKhaoSat: 'khu-pho_tuyen-truyen-phan-anh_khao-sat',
  khuPhoTuyenTruyenPhanAnhPhanAnh: 'khu-pho_tuyen-truyen-phan-anh_phan-anh',
  khuPhoCongViec: 'khu-pho_cong-viec',
  khuPhoCongViecCuocHop: 'khu-pho_cong-viec_cuoc-hop',
  khuPhoCongViecNhiemVu: 'khu-pho_cong-viec_nhiem-vu',
  khuPhoCongViecNhiemVuCuaToi: 'khu-pho_nhiem-vu_nhiem-vu-cua-toi',
  khuPhoCongViecTaiChinh: 'khu-pho_cong-viec_tai-chinh',
  khuPhoCongViecBaoHiemYTe: 'khu-pho_cong-viec_bao-hiem-y-te',
} as const;